#!/usr/bin/env node
// Auto-generate catalog.md (llms.txt-style index) from the skills on disk.
// Deterministic, so the catalog never drifts from reality. Usage: node gen-catalog.mjs
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { listSkillDirs, parseSkill, SKILLS_DIR } from './lib.mjs';

const order = { router: 0, knowledge: 1, task: 2, meta: 3 };
const skills = listSkillDirs().map((n) => {
  const s = parseSkill(n);
  return { name: n, type: s.fm.metadata?.type || '?', desc: (s.fm.description || '').trim() };
});
skills.sort((a, b) => (order[a.type] ?? 9) - (order[b.type] ?? 9) || a.name.localeCompare(b.name));

let out =
  '# Skills Catalog — newsletter-crawler\n\n' +
  '> Auto-generated by `scripts/gen-catalog.mjs` (do not hand-edit). ' +
  'Every implementation task goes through `project-router`.\n';
let curType = null;
for (const s of skills) {
  if (s.type !== curType) {
    out += `\n## ${s.type}\n\n`;
    curType = s.type;
  }
  out += `- **${s.name}** — ${s.desc}\n`;
}
out +=
  '\n## Tooling\n' +
  '- Lint all skills: `node .agents/skills/scripts/skill-lint.mjs --all`\n' +
  '- Validate/evaluate a skill (writes token): `node .agents/skills/scripts/skill-eval.mjs <name>`\n' +
  '- Evolve a skill safely: `node .agents/skills/scripts/validate-skill.mjs <name>` (promotes SKILL.md.next)\n' +
  '- Regenerate this catalog: `node .agents/skills/scripts/gen-catalog.mjs`\n';

writeFileSync(path.join(SKILLS_DIR, 'catalog.md'), out);
console.log(`catalog.md written (${skills.length} skills)`);
